FROM hashicorp/terraform:%%TERRAFORM_VERSION%%
MAINTAINER Azavea <systems@azavea.com>

RUN \
    apk add --no-cache \
        bash \
        jq \
        make \
        python3 \
        py-pip \
        zip \
    && pip install awscli
