FROM hashicorp/terraform:%%TERRAFORM_VERSION%%

RUN \
    apk add --no-cache \
        bash \
        jq \
        make \
        python3 \
        py-pip \
        zip \
        curl \
    && pip3 install awscli
