#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

set -u

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build container images from templates.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else

        sed -e "s/%%TERRAFORM_VERSION%%/${TERRAFORM_VERSION}/" \
            "Dockerfile.template" >Dockerfile

        docker \
            build -t "quay.io/azavea/terraform:${TERRAFORM_VERSION}" .

        ./scripts/test

        docker images
    fi
fi
